/************ Update: Schemas ***************/

COMMENT ON SCHEMA public IS 'Sistema de Información Agricola';



/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE public.bda_avance_agua_surco_aas_item_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_avance_agua_surco_aas_item_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_bitacora_bit_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_bitacora_bit_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_cargo_car_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_cargo_car_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_contro_riego_pluviosidad_crp_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_contro_riego_pluviosidad_crp_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_control_administrativo_riego_car_num_documento_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_control_administrativo_riego_car_num_documento_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_control_salida_cana_csc_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_control_salida_cana_csc_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_dato_usuario_dus_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_dato_usuario_dus_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_detalle_agua_surco_deaas_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_detalle_agua_surco_deaas_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_detalle_caudal_surco_decs_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_detalle_caudal_surco_decs_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_detalle_ejecucion_dee_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_detalle_ejecucion_dee_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_detalle_entrada_salida_bodega_des_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_detalle_entrada_salida_bodega_des_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_detalle_orden_deo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_detalle_orden_deo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_detalle_registro_der_item_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_detalle_registro_der_item_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_entrada_salida_bodega_esb_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_entrada_salida_bodega_esb_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_hacienda_hac_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_hacienda_hac_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_implemento_imp_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_implemento_imp_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_inventario_inv_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_inventario_inv_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_labor_lab_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_labor_lab_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_labores_maquina_equipo_lme_numero_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_labores_maquina_equipo_lme_numero_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_maquina_maq_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_maquina_maq_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_marca_mar_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_marca_mar_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_metodo_riego_met_rie_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_metodo_riego_met_rie_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_orden_ejecucion_ore_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_orden_ejecucion_ore_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_orden_servicio_ors_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_orden_servicio_ors_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_producto_pro_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_producto_pro_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_recordar_me_rcm_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_recordar_me_rcm_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_registro_tractor_rtritem_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_registro_tractor_rtritem_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_rol_rol_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_rol_rol_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_servicio_maquina_ser_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_servicio_maquina_ser_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_siembra_sie_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_siembra_sie_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_suerte_sue_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_suerte_sue_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tercero_ter_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tercero_ter_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tipo_cana_tic_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tipo_cana_tic_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tipo_documento_tpd_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tipo_documento_tpd_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tipo_id_tpi_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tipo_id_tpi_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tipo_mantenimiento_tma_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tipo_mantenimiento_tma_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tipo_producto_tpr_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tipo_producto_tpr_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tipo_suelo_tis_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tipo_suelo_tis_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_tipo_tercero_tit_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_tipo_tercero_tit_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_turno_tur_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_turno_tur_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_unidad_medida_unm_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_unidad_medida_unm_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_usuario_usr_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_usuario_usr_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.bda_usuario_rol_url_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.bda_usuario_rol_url_id_seq IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: public.bda_avance_agua_surco ************************/

/* Build Table Structure */
CREATE TABLE public.bda_avance_agua_surco
(
	aas_item BIGINT DEFAULT nextval('public.bda_avance_agua_surco_aas_item_seq'::regclass) NOT NULL,
	car_num_documento BIGINT NOT NULL,
	aas_surco_id BIGINT NOT NULL,
	aas_created_at TIMESTAMP DEFAULT now() NOT NULL,
	aas_updated_at TIMESTAMP NULL,
	aas_deleted_at TIMESTAMP NULL
);

/* Add Primary Key */
ALTER TABLE public.bda_avance_agua_surco ADD CONSTRAINT pkbda_avance_agua_surco
	PRIMARY KEY (aas_item);


/******************** Add Table: public.bda_bitacora ************************/

/* Build Table Structure */
CREATE TABLE public.bda_bitacora
(
	bit_id BIGINT DEFAULT nextval('public.bda_bitacora_bit_id_seq'::regclass) NOT NULL,
	usr_id BIGINT NOT NULL,
	bit_accion VARCHAR(80) NOT NULL,
	bit_tabla VARCHAR(80) NOT NULL,
	bit_registro BIGINT NULL,
	bit_observacion VARCHAR(1024) NULL,
	bit_fecha TIMESTAMP DEFAULT now() NOT NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_bitacora ADD CONSTRAINT pkbda_bitacora
	PRIMARY KEY (bit_id);

/* Add Indexes */
CREATE INDEX "bda_bitacora_bit_fecha_Idx" ON public.bda_bitacora USING btree (bit_fecha);

CREATE INDEX "bda_bitacora_usr_id_Idx" ON public.bda_bitacora USING btree (usr_id);


/******************** Add Table: public.bda_cargo ************************/

/* Build Table Structure */
CREATE TABLE public.bda_cargo
(
	car_id BIGINT DEFAULT nextval('public.bda_cargo_car_id_seq'::regclass) NOT NULL,
	car_descripcion VARCHAR(80) NOT NULL,
	car_created_at TIMESTAMP DEFAULT now() NOT NULL,
	car_updated_at TIMESTAMP NULL,
	car_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_cargo ADD CONSTRAINT pkbda_cargo
	PRIMARY KEY (car_id);


/******************** Add Table: public.bda_contro_riego_pluviosidad ************************/

/* Build Table Structure */
CREATE TABLE public.bda_contro_riego_pluviosidad
(
	crp_id BIGINT DEFAULT nextval('public.bda_contro_riego_pluviosidad_crp_id_seq'::regclass) NOT NULL,
	crp_fecha DATE NOT NULL,
	crp_hora_inicio TIME NOT NULL,
	crp_hora_fin TIME NOT NULL,
	crp_cantidad_m3_hora INTEGER DEFAULT 0 NOT NULL,
	crp_observacion TEXT NULL,
	sue_id BIGINT NOT NULL,
	hac_id BIGINT NOT NULL,
	ter_id BIGINT NOT NULL,
	crp_created_at TIMESTAMP DEFAULT now() NOT NULL,
	crp_updated_at TIMESTAMP NULL,
	crp_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_contro_riego_pluviosidad ADD CONSTRAINT pkbda_contro_riego_pluviosidad
	PRIMARY KEY (crp_id);


/******************** Add Table: public.bda_control_administrativo_riego ************************/

/* Build Table Structure */
CREATE TABLE public.bda_control_administrativo_riego
(
	car_num_documento BIGINT DEFAULT nextval('public.bda_control_administrativo_riego_car_num_documento_seq'::regclass) NOT NULL,
	car_fecha DATE NOT NULL,
	met_rie_id BIGINT NOT NULL,
	hac_id BIGINT NOT NULL,
	sue_id BIGINT NOT NULL,
	car_caudal_riego INTEGER DEFAULT 0 NOT NULL,
	car_tiempo_riego VARCHAR(5) NOT NULL,
	car_tiempo_total_suspension VARCHAR(5) NOT NULL,
	car_longitud_surco INTEGER DEFAULT 0 NOT NULL,
	car_espacio_surco INTEGER DEFAULT 0 NOT NULL,
	car_num_surco_regados INTEGER DEFAULT 0 NOT NULL,
	car_estado_humedad VARCHAR(80) NOT NULL,
	car_suelo_grieta BOOL NOT NULL,
	car_facil_avance_agua BOOL NOT NULL,
	car_pendiente_dir_surco VARCHAR(80) NOT NULL,
	car_agua_costado BOOL NOT NULL,
	car_created_at TIMESTAMP DEFAULT now() NOT NULL,
	car_updated_at TIMESTAMP NULL,
	car_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_control_administrativo_riego ADD CONSTRAINT pkbda_control_administrativo_riego
	PRIMARY KEY (car_num_documento);

/* Add Comments */
COMMENT ON COLUMN public.bda_control_administrativo_riego.car_tiempo_riego IS 'hh:mm';

COMMENT ON COLUMN public.bda_control_administrativo_riego.car_tiempo_total_suspension IS 'hh:mm';

COMMENT ON COLUMN public.bda_control_administrativo_riego.car_longitud_surco IS 'metros';

COMMENT ON COLUMN public.bda_control_administrativo_riego.car_suelo_grieta IS 'true = si | false = no';

COMMENT ON COLUMN public.bda_control_administrativo_riego.car_facil_avance_agua IS 'true = si | false = no';

COMMENT ON COLUMN public.bda_control_administrativo_riego.car_agua_costado IS 'true = si | false = no';


/******************** Add Table: public.bda_control_salida_cana ************************/

/* Build Table Structure */
CREATE TABLE public.bda_control_salida_cana
(
	csc_id BIGINT DEFAULT nextval('public.bda_control_salida_cana_csc_id_seq'::regclass) NOT NULL,
	csc_fecha DATE NOT NULL,
	csc_total_vagones INTEGER DEFAULT 0 NOT NULL,
	csc_notas TEXT NULL,
	csc_total_trenes INTEGER DEFAULT 0 NOT NULL,
	tur_id BIGINT NOT NULL,
	sue_id BIGINT NOT NULL,
	ter_id BIGINT NOT NULL,
	csc_created_at TIMESTAMP DEFAULT now() NOT NULL,
	csc_updated_at TIMESTAMP NULL,
	csc_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_control_salida_cana ADD CONSTRAINT pkbda_control_salida_cana
	PRIMARY KEY (csc_id);


/******************** Add Table: public.bda_dato_usuario ************************/

/* Build Table Structure */
CREATE TABLE public.bda_dato_usuario
(
	dus_id BIGINT DEFAULT nextval('public.bda_dato_usuario_dus_id_seq'::regclass) NOT NULL,
	usr_id BIGINT NOT NULL,
	dus_cedula VARCHAR(20) NOT NULL,
	dus_nombre VARCHAR(80) NOT NULL,
	dus_apellidos VARCHAR(80) NOT NULL,
	dus_movil VARCHAR(12) NOT NULL,
	dus_correo VARCHAR(120) NOT NULL,
	dus_imagen VARCHAR(36) NULL,
	dus_sexo BOOL NOT NULL,
	dus_created_at TIMESTAMP DEFAULT now() NOT NULL,
	dus_updated_at TIMESTAMP NULL,
	dus_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_dato_usuario ADD CONSTRAINT pkbda_dato_usuario
	PRIMARY KEY (dus_id);

/* Add Comments */
COMMENT ON COLUMN public.bda_dato_usuario.dus_sexo IS 't = masculino ; f = femenino';

/* Add Indexes */
CREATE UNIQUE INDEX "bda_dato_usuario_dus_correo_Idx" ON public.bda_dato_usuario USING btree (dus_correo);

CREATE INDEX "bda_dato_usuario_dus_deleted_at_Idx" ON public.bda_dato_usuario USING btree (dus_deleted_at);

CREATE UNIQUE INDEX "bda_dato_usuario_usr_id_Idx" ON public.bda_dato_usuario USING btree (usr_id);


/******************** Add Table: public.bda_detalle_agua_surco ************************/

/* Build Table Structure */
CREATE TABLE public.bda_detalle_agua_surco
(
	deaas_id BIGINT DEFAULT nextval('public.bda_detalle_agua_surco_deaas_id_seq'::regclass) NOT NULL,
	deaas_item VARCHAR(80) NOT NULL,
	deaas_cantidad_surco INTEGER DEFAULT 0 NOT NULL,
	fore_num_documento BIGINT NOT NULL,
	deaas_created_at TIMESTAMP DEFAULT now() NOT NULL,
	deaas_updated_at TIMESTAMP NULL,
	deaas_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_detalle_agua_surco ADD CONSTRAINT pkbda_detalle_agua_surco
	PRIMARY KEY (deaas_id);


/******************** Add Table: public.bda_detalle_caudal_surco ************************/

/* Build Table Structure */
CREATE TABLE public.bda_detalle_caudal_surco
(
	decs_id BIGINT DEFAULT nextval('public.bda_detalle_caudal_surco_decs_id_seq'::regclass) NOT NULL,
	decs_item VARCHAR(80) NOT NULL,
	decs_cantidad_surco INTEGER DEFAULT 0 NOT NULL,
	fore_num_documento BIGINT NOT NULL,
	decs_created_at TIMESTAMP DEFAULT now() NOT NULL,
	decs_updated_at TIMESTAMP NULL,
	decs_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_detalle_caudal_surco ADD CONSTRAINT pkbda_detalle_caudal_surco
	PRIMARY KEY (decs_id);


/******************** Add Table: public.bda_detalle_ejecucion ************************/

/* Build Table Structure */
CREATE TABLE public.bda_detalle_ejecucion
(
	dee_id BIGINT DEFAULT nextval('public.bda_detalle_ejecucion_dee_id_seq'::regclass) NOT NULL,
	ore_id BIGINT NOT NULL,
	ter_id BIGINT NOT NULL,
	ser_id BIGINT NOT NULL,
	pro_id BIGINT NOT NULL,
	dee_cantidad INTEGER DEFAULT 0 NOT NULL,
	dee_precio BIGINT DEFAULT 0 NOT NULL,
	dee_created_at TIMESTAMP DEFAULT now() NOT NULL,
	dee_updated_at TIMESTAMP NULL,
	dee_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_detalle_ejecucion ADD CONSTRAINT pkbda_detalle_ejecucion
	PRIMARY KEY (dee_id);


/******************** Add Table: public.bda_detalle_entrada_salida_bodega ************************/

/* Build Table Structure */
CREATE TABLE public.bda_detalle_entrada_salida_bodega
(
	des_id BIGINT DEFAULT nextval('public.bda_detalle_entrada_salida_bodega_des_id_seq'::regclass) NOT NULL,
	esb_id BIGINT NOT NULL,
	pro_id BIGINT NOT NULL,
	unm_id BIGINT NOT NULL,
	des_cantidad INTEGER DEFAULT 0 NOT NULL,
	des_precio BIGINT DEFAULT 0 NOT NULL,
	des_created_at TIMESTAMP DEFAULT now() NOT NULL,
	des_updated_at TIMESTAMP NULL,
	des_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_detalle_entrada_salida_bodega ADD CONSTRAINT pkbda_detalle_entrada_salida_bodega
	PRIMARY KEY (des_id);


/******************** Add Table: public.bda_detalle_orden ************************/

/* Build Table Structure */
CREATE TABLE public.bda_detalle_orden
(
	deo_id BIGINT DEFAULT nextval('public.bda_detalle_orden_deo_id_seq'::regclass) NOT NULL,
	ors_id BIGINT NOT NULL,
	ser_id BIGINT NOT NULL,
	deo_created_at TIMESTAMP DEFAULT now() NOT NULL,
	deo_updated_at TIMESTAMP NULL,
	deo_deleted_at TIMESTAMP NULL,
	deo_estado BOOL NOT NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_detalle_orden ADD CONSTRAINT pkbda_detalle_orden
	PRIMARY KEY (deo_id);

/* Add Comments */
COMMENT ON COLUMN public.bda_detalle_orden.deo_estado IS 'true = realizado | false = no realizado';


/******************** Add Table: public.bda_detalle_registro ************************/

/* Build Table Structure */
CREATE TABLE public.bda_detalle_registro
(
	der_item BIGINT DEFAULT nextval('public.bda_detalle_registro_der_item_seq'::regclass) NOT NULL,
	relme_numero BIGINT NOT NULL,
	ter_id BIGINT NOT NULL,
	lab_id BIGINT NOT NULL,
	sue_id BIGINT NOT NULL,
	pro_id BIGINT NOT NULL,
	unm_id BIGINT NOT NULL,
	maq_id BIGINT NOT NULL,
	der_tiempo_muerto BIGINT DEFAULT 0 NOT NULL,
	der_total_horas_trabajadas BIGINT DEFAULT 0 NOT NULL,
	der_hora_inicio TIME NOT NULL,
	der_hora_fin TIME NOT NULL,
	der_cantidad BIGINT DEFAULT 0 NOT NULL,
	der_created_at TIMESTAMP DEFAULT now() NOT NULL,
	der_updated_at TIMESTAMP NULL,
	der_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT pkbda_detalle_registro
	PRIMARY KEY (der_item);


/******************** Add Table: public.bda_entrada_salida_bodega ************************/

/* Build Table Structure */
CREATE TABLE public.bda_entrada_salida_bodega
(
	esb_id BIGINT DEFAULT nextval('public.bda_entrada_salida_bodega_esb_id_seq'::regclass) NOT NULL,
	ter_id_elabora BIGINT NOT NULL,
	ter_id_solicita BIGINT NOT NULL,
	tpd_id BIGINT NOT NULL,
	esb_fecha DATE NOT NULL,
	esb_observacion VARCHAR(1024) NULL,
	esb_created_at TIMESTAMP DEFAULT now() NOT NULL,
	esb_updated_at TIMESTAMP NULL,
	esb_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_entrada_salida_bodega ADD CONSTRAINT pkbda_entrada_salida_bodega
	PRIMARY KEY (esb_id);


/******************** Add Table: public.bda_hacienda ************************/

/* Build Table Structure */
CREATE TABLE public.bda_hacienda
(
	hac_id BIGINT DEFAULT nextval('public.bda_hacienda_hac_id_seq'::regclass) NOT NULL,
	hac_descripcion VARCHAR(80) NOT NULL,
	hac_ubicacion VARCHAR(100) NOT NULL,
	hac_representante_legal VARCHAR(100) NOT NULL,
	hac_created_at TIMESTAMP DEFAULT now() NOT NULL,
	hac_updated_at TIMESTAMP NULL,
	hac_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_hacienda ADD CONSTRAINT pkbda_hacienda
	PRIMARY KEY (hac_id);


/******************** Add Table: public.bda_implemento ************************/

/* Build Table Structure */
CREATE TABLE public.bda_implemento
(
	imp_id BIGINT DEFAULT nextval('public.bda_implemento_imp_id_seq'::regclass) NOT NULL,
	imp_descripcion VARCHAR(80) NOT NULL,
	imp_created_at TIMESTAMP DEFAULT now() NOT NULL,
	imp_updated_at TIMESTAMP NULL,
	imp_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_implemento ADD CONSTRAINT pkbda_implemento
	PRIMARY KEY (imp_id);


/******************** Add Table: public.bda_inventario ************************/

/* Build Table Structure */
CREATE TABLE public.bda_inventario
(
	inv_id BIGINT DEFAULT nextval('public.bda_inventario_inv_id_seq'::regclass) NOT NULL,
	pro_id BIGINT NOT NULL,
	tpd_id BIGINT NOT NULL,
	inv_num_doc BIGINT NOT NULL,
	inv_fecha DATE NOT NULL,
	inv_cantidad INTEGER DEFAULT 0 NOT NULL,
	inv_movimiento VARCHAR(80) NOT NULL,
	inv_saldo INTEGER DEFAULT 0 NOT NULL,
	inv_created_at TIMESTAMP DEFAULT now() NOT NULL,
	inv_updated_at TIMESTAMP NULL,
	inv_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_inventario ADD CONSTRAINT pkbda_inventario
	PRIMARY KEY (inv_id);


/******************** Add Table: public.bda_labor ************************/

/* Build Table Structure */
CREATE TABLE public.bda_labor
(
	lab_id BIGINT DEFAULT nextval('public.bda_labor_lab_id_seq'::regclass) NOT NULL,
	lab_descripcion VARCHAR(80) NOT NULL,
	lab_valor BIGINT DEFAULT 0 NOT NULL,
	lab_estado VARCHAR(30) NOT NULL,
	lab_created_at TIMESTAMP DEFAULT now() NOT NULL,
	lab_updated_at TIMESTAMP NULL,
	lab_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_labor ADD CONSTRAINT pkbda_labor
	PRIMARY KEY (lab_id);


/******************** Add Table: public.bda_labores_maquina_equipo ************************/

/* Build Table Structure */
CREATE TABLE public.bda_labores_maquina_equipo
(
	lme_numero BIGINT DEFAULT nextval('public.bda_labores_maquina_equipo_lme_numero_seq'::regclass) NOT NULL,
	hac_id BIGINT NOT NULL,
	ter_id BIGINT NOT NULL,
	tpd_id BIGINT NOT NULL,
	imp_id BIGINT NOT NULL,
	lme_fecha DATE NOT NULL,
	lme_estado BOOL DEFAULT 't' NOT NULL,
	lme_tiempo INTEGER NOT NULL,
	lme_total_horas_trabajadas INTEGER NOT NULL,
	lme_created_at TIMESTAMP DEFAULT now() NOT NULL,
	lme_updated_at TIMESTAMP NULL,
	lme_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_labores_maquina_equipo ADD CONSTRAINT pkbda_labores_maquina_equipo
	PRIMARY KEY (lme_numero);

/* Add Comments */
COMMENT ON COLUMN public.bda_labores_maquina_equipo.lme_estado IS 't = true | f = false';


/******************** Add Table: public.bda_maquina ************************/

/* Build Table Structure */
CREATE TABLE public.bda_maquina
(
	maq_id BIGINT DEFAULT nextval('public.bda_maquina_maq_id_seq'::regclass) NOT NULL,
	maq_estado VARCHAR(30) NOT NULL,
	maq_valor BIGINT DEFAULT 0 NOT NULL,
	maq_fecha_compra DATE NOT NULL,
	maq_numero_chasis VARCHAR(80) NOT NULL,
	maq_tipo_accesorio VARCHAR(80) NOT NULL,
	maq_horas_trabajadas BIGINT DEFAULT 0 NOT NULL,
	maq_tiempo_mantenimiento_hora BIGINT DEFAULT 0 NOT NULL,
	maq_numero_serie VARCHAR(80) NOT NULL,
	maq_modelo VARCHAR(80) NOT NULL,
	maq_horas_actividad BIGINT DEFAULT 0 NOT NULL,
	maq_valor_hora BIGINT DEFAULT 0 NOT NULL,
	maq_created_at TIMESTAMP DEFAULT now() NOT NULL,
	maq_updated_at TIMESTAMP NULL,
	maq_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_maquina ADD CONSTRAINT pkbda_maquina
	PRIMARY KEY (maq_id);


/******************** Add Table: public.bda_marca ************************/

/* Build Table Structure */
CREATE TABLE public.bda_marca
(
	mar_id BIGINT DEFAULT nextval('public.bda_marca_mar_id_seq'::regclass) NOT NULL,
	mar_descripcion VARCHAR(80) NOT NULL,
	mar_created_at TIMESTAMP DEFAULT now() NOT NULL,
	mar_updated_at TIMESTAMP NULL,
	mar_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_marca ADD CONSTRAINT pkbda_marca
	PRIMARY KEY (mar_id);


/******************** Add Table: public.bda_metodo_riego ************************/

/* Build Table Structure */
CREATE TABLE public.bda_metodo_riego
(
	met_rie_id BIGINT DEFAULT nextval('public.bda_metodo_riego_met_rie_id_seq'::regclass) NOT NULL,
	met_rie_descripcion VARCHAR(80) NOT NULL,
	met_created_at TIMESTAMP DEFAULT now() NOT NULL,
	met_updated_at TIMESTAMP NULL,
	met_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_metodo_riego ADD CONSTRAINT pkbda_metodo_riego
	PRIMARY KEY (met_rie_id);


/******************** Add Table: public.bda_orden_ejecucion ************************/

/* Build Table Structure */
CREATE TABLE public.bda_orden_ejecucion
(
	ore_id BIGINT DEFAULT nextval('public.bda_orden_ejecucion_ore_id_seq'::regclass) NOT NULL,
	ter_id_elabora BIGINT NOT NULL,
	ors_id BIGINT NOT NULL,
	maq_id BIGINT NOT NULL,
	ore_fecha DATE NOT NULL,
	ore_observacion VARCHAR(1024) NULL,
	ore_created_at TIMESTAMP DEFAULT now() NOT NULL,
	ore_updated_at TIMESTAMP NULL,
	ore_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_orden_ejecucion ADD CONSTRAINT pkbda_orden_ejecucion
	PRIMARY KEY (ore_id);


/******************** Add Table: public.bda_orden_servicio ************************/

/* Build Table Structure */
CREATE TABLE public.bda_orden_servicio
(
	ors_id BIGINT DEFAULT nextval('public.bda_orden_servicio_ors_id_seq'::regclass) NOT NULL,
	maq_id BIGINT NOT NULL,
	tma_id BIGINT NOT NULL,
	ter_id_elabora BIGINT NOT NULL,
	ter_id_realiza BIGINT NOT NULL,
	ors_fecha DATE NOT NULL,
	ors_observacion VARCHAR(1024) NULL,
	ors_created_at TIMESTAMP DEFAULT now() NOT NULL,
	ors_updated_at TIMESTAMP NULL,
	ors_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_orden_servicio ADD CONSTRAINT pkbda_orden_servicio
	PRIMARY KEY (ors_id);


/******************** Add Table: public.bda_producto ************************/

/* Build Table Structure */
CREATE TABLE public.bda_producto
(
	pro_id BIGINT DEFAULT nextval('public.bda_producto_pro_id_seq'::regclass) NOT NULL,
	pro_descripcion VARCHAR(80) NOT NULL,
	tpr_id BIGINT NOT NULL,
	mar_id BIGINT NOT NULL,
	unm_id BIGINT NOT NULL,
	pro_created_at TIMESTAMP DEFAULT now() NOT NULL,
	pro_updated_at TIMESTAMP NULL,
	pro_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_producto ADD CONSTRAINT pkbda_producto
	PRIMARY KEY (pro_id);


/******************** Add Table: public.bda_recordar_me ************************/

/* Build Table Structure */
CREATE TABLE public.bda_recordar_me
(
	rcm_id BIGINT DEFAULT nextval('public.bda_recordar_me_rcm_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	rcm_ip_address VARCHAR(50) NOT NULL,
	rcm_hash_cookie VARCHAR(32) NOT NULL,
	rcm_created_at TIMESTAMP DEFAULT now() NOT NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_recordar_me ADD CONSTRAINT pkbda_recordar_me
	PRIMARY KEY (rcm_id);

/* Add Indexes */
CREATE UNIQUE INDEX "bda_recordar_me_rcm_ip_address_rcm_hash_cookie_Idx" ON public.bda_recordar_me USING btree (rcm_ip_address, rcm_hash_cookie);

CREATE INDEX "bda_recordar_me_usuario_id_Idx" ON public.bda_recordar_me USING btree (usuario_id);


/******************** Add Table: public.bda_registro_tractor ************************/

/* Build Table Structure */
CREATE TABLE public.bda_registro_tractor
(
	rtritem BIGINT DEFAULT nextval('public.bda_registro_tractor_rtritem_seq'::regclass) NOT NULL,
	csc_id BIGINT NOT NULL,
	rtrhora_salida TIME NOT NULL,
	rtrtractor VARCHAR(80) NOT NULL,
	rtrobservacion TEXT NULL,
	rtrcreated_at TIMESTAMP DEFAULT now() NOT NULL,
	rtrupdated_at TIMESTAMP NULL,
	rtrdeleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_registro_tractor ADD CONSTRAINT pkbda_registro_tractor
	PRIMARY KEY (rtritem);


/******************** Add Table: public.bda_rol ************************/

/* Build Table Structure */
CREATE TABLE public.bda_rol
(
	rol_id BIGINT DEFAULT nextval('public.bda_rol_rol_id_seq'::regclass) NOT NULL,
	rol_nombre VARCHAR(80) NOT NULL,
	rol_created_at TIMESTAMP DEFAULT now() NOT NULL,
	rol_updated_at TIMESTAMP NULL,
	rol_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_rol ADD CONSTRAINT pkbda_rol
	PRIMARY KEY (rol_id);

/* Add Indexes */
CREATE INDEX "bda_rol_deleted_at_Idx" ON public.bda_rol USING btree (rol_deleted_at);


/******************** Add Table: public.bda_servicio_maquina ************************/

/* Build Table Structure */
CREATE TABLE public.bda_servicio_maquina
(
	ser_id BIGINT DEFAULT nextval('public.bda_servicio_maquina_ser_id_seq'::regclass) NOT NULL,
	ser_descripcion VARCHAR(80) NOT NULL,
	ser_estado VARCHAR(30) NOT NULL,
	ser_created_at TIMESTAMP DEFAULT now() NOT NULL,
	ser_updated_at TIMESTAMP NULL,
	ser_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_servicio_maquina ADD CONSTRAINT pkbda_servicio_maquina
	PRIMARY KEY (ser_id);


/******************** Add Table: public.bda_siembra ************************/

/* Build Table Structure */
CREATE TABLE public.bda_siembra
(
	sie_id BIGINT DEFAULT nextval('public.bda_siembra_sie_id_seq'::regclass) NOT NULL,
	sue_id BIGINT NOT NULL,
	tic_id BIGINT NOT NULL,
	sie_dia INTEGER NOT NULL,
	sie_presupuesto_empresa INTEGER NOT NULL,
	sie_kilos_lote INTEGER NOT NULL,
	sie_total_kilos_planta INTEGER NOT NULL,
	sie_fecha DATE NOT NULL,
	sie_fecha_fin_levante DATE NOT NULL,
	sie_fecha_inicio_ciclo DATE NOT NULL,
	sie_fecha_fin_ciclo DATE NOT NULL,
	sie_fecha_poda DATE NOT NULL,
	sie_fecha_produccion DATE NOT NULL,
	sie_num_hectarea INTEGER NOT NULL,
	sie_num_planta_levante INTEGER NOT NULL,
	sie_num_plantas_productivas INTEGER NOT NULL,
	sie_num_plantas_erradica INTEGER NOT NULL,
	sie_created_at TIMESTAMP DEFAULT now() NOT NULL,
	sie_updated_at TIMESTAMP NULL,
	sie_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_siembra ADD CONSTRAINT pkbda_siembra
	PRIMARY KEY (sie_id);


/******************** Add Table: public.bda_suerte ************************/

/* Build Table Structure */
CREATE TABLE public.bda_suerte
(
	sue_id BIGINT DEFAULT nextval('public.bda_suerte_sue_id_seq'::regclass) NOT NULL,
	sue_descripcion VARCHAR(80) NOT NULL,
	sue_area INTEGER DEFAULT 0 NOT NULL,
	tis_id BIGINT NOT NULL,
	sue_created_at TIMESTAMP DEFAULT now() NOT NULL,
	sue_updated_at TIMESTAMP NULL,
	sue_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_suerte ADD CONSTRAINT pkbda_suerte
	PRIMARY KEY (sue_id);


/******************** Add Table: public.bda_tercero ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tercero
(
	ter_id BIGINT DEFAULT nextval('public.bda_tercero_ter_id_seq'::regclass) NOT NULL,
	ter_nombre VARCHAR(80) NOT NULL,
	ter_apellido VARCHAR(80) NOT NULL,
	ter_telefono VARCHAR(20) NOT NULL,
	ter_direccion VARCHAR(100) NOT NULL,
	ter_correo VARCHAR(100) NULL,
	car_id BIGINT NOT NULL,
	tpi_id BIGINT NOT NULL,
	tit_id BIGINT NOT NULL,
	ter_created_at TIMESTAMP DEFAULT now() NOT NULL,
	ter_updated_at TIMESTAMP NULL,
	ter_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_tercero ADD CONSTRAINT pkbda_tercero
	PRIMARY KEY (ter_id);


/******************** Add Table: public.bda_tipo_cana ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tipo_cana
(
	tic_id BIGINT DEFAULT nextval('public.bda_tipo_cana_tic_id_seq'::regclass) NOT NULL,
	tic_descripcion VARCHAR(80) NOT NULL,
	tic_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tic_updated_at TIMESTAMP NULL,
	tic_deleted_at TIMESTAMP NULL
);

/* Add Primary Key */
ALTER TABLE public.bda_tipo_cana ADD CONSTRAINT pkbda_tipo_cana
	PRIMARY KEY (tic_id);


/******************** Add Table: public.bda_tipo_documento ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tipo_documento
(
	tpd_id BIGINT DEFAULT nextval('public.bda_tipo_documento_tpd_id_seq'::regclass) NOT NULL,
	tpd_descripcion VARCHAR(80) NOT NULL,
	tpd_tipo_movimiento VARCHAR(80) NOT NULL,
	tpd_estado BOOL DEFAULT 't' NOT NULL,
	tdp_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tdp_updated_at TIMESTAMP NULL,
	tdp_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_tipo_documento ADD CONSTRAINT pkbda_tipo_documento
	PRIMARY KEY (tpd_id);

/* Add Comments */
COMMENT ON COLUMN public.bda_tipo_documento.tpd_estado IS 't = true | f = false';


/******************** Add Table: public.bda_tipo_id ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tipo_id
(
	tpi_id BIGINT DEFAULT nextval('public.bda_tipo_id_tpi_id_seq'::regclass) NOT NULL,
	tpi_descripcion VARCHAR(80) NOT NULL,
	tpi_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tpi_updated_at TIMESTAMP NULL,
	tpi_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_tipo_id ADD CONSTRAINT pkbda_tipo_id
	PRIMARY KEY (tpi_id);


/******************** Add Table: public.bda_tipo_mantenimiento ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tipo_mantenimiento
(
	tma_id BIGINT DEFAULT nextval('public.bda_tipo_mantenimiento_tma_id_seq'::regclass) NOT NULL,
	tma_descripcion VARCHAR(80) NOT NULL,
	tma_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tma_updated_at TIMESTAMP NULL,
	tma_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_tipo_mantenimiento ADD CONSTRAINT pkbda_tipo_mantenimiento
	PRIMARY KEY (tma_id);


/******************** Add Table: public.bda_tipo_producto ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tipo_producto
(
	tpr_id BIGINT DEFAULT nextval('public.bda_tipo_producto_tpr_id_seq'::regclass) NOT NULL,
	tpr_descripcion VARCHAR(80) NOT NULL,
	tpr_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tpr_updated_at TIMESTAMP NULL,
	tpr_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_tipo_producto ADD CONSTRAINT pkbda_tipo_producto
	PRIMARY KEY (tpr_id);


/******************** Add Table: public.bda_tipo_suelo ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tipo_suelo
(
	tis_id BIGINT DEFAULT nextval('public.bda_tipo_suelo_tis_id_seq'::regclass) NOT NULL,
	tis_descripcion VARCHAR(80) NOT NULL,
	tis_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tis_updated_at TIMESTAMP NULL,
	tis_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_tipo_suelo ADD CONSTRAINT pkbda_tipo_suelo
	PRIMARY KEY (tis_id);


/******************** Add Table: public.bda_tipo_tercero ************************/

/* Build Table Structure */
CREATE TABLE public.bda_tipo_tercero
(
	tit_id BIGINT DEFAULT nextval('public.bda_tipo_tercero_tit_id_seq'::regclass) NOT NULL,
	tit_descripcion VARCHAR(80) NOT NULL,
	tit_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tit_updated_at TIMESTAMP NULL,
	tit_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_tipo_tercero ADD CONSTRAINT pkbda_tipo_tercero
	PRIMARY KEY (tit_id);


/******************** Add Table: public.bda_turno ************************/

/* Build Table Structure */
CREATE TABLE public.bda_turno
(
	tur_id BIGINT DEFAULT nextval('public.bda_turno_tur_id_seq'::regclass) NOT NULL,
	tur_descripcion VARCHAR(80) NOT NULL,
	tur_hora_inicio TIME NOT NULL,
	tur_hora_fin TIME NOT NULL,
	tur_estado VARCHAR(80) NOT NULL,
	tur_created_at TIMESTAMP DEFAULT now() NOT NULL,
	tur_updated_at TIMESTAMP NULL,
	tur_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_turno ADD CONSTRAINT pkbda_turno
	PRIMARY KEY (tur_id);


/******************** Add Table: public.bda_unidad_medida ************************/

/* Build Table Structure */
CREATE TABLE public.bda_unidad_medida
(
	unm_id BIGINT DEFAULT nextval('public.bda_unidad_medida_unm_id_seq'::regclass) NOT NULL,
	unm_descripcion VARCHAR(80) NOT NULL,
	unm_created_at TIMESTAMP DEFAULT now() NOT NULL,
	unm_updated_at TIMESTAMP NULL,
	unm_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_unidad_medida ADD CONSTRAINT pkbda_unidad_medida
	PRIMARY KEY (unm_id);


/******************** Add Table: public.bda_usuario ************************/

/* Build Table Structure */
CREATE TABLE public.bda_usuario
(
	usr_id BIGINT DEFAULT nextval('public.bda_usuario_usr_id_seq'::regclass) NOT NULL,
	usr_user VARCHAR(80) NOT NULL,
	usr_password VARCHAR(32) NOT NULL,
	usr_actived BOOL DEFAULT 't' NOT NULL,
	usr_last_login_at TIMESTAMP NULL,
	usr_created_at TIMESTAMP DEFAULT now() NOT NULL,
	usr_updated_at TIMESTAMP NULL,
	usr_deleted_at TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_usuario ADD CONSTRAINT pkbda_usuario
	PRIMARY KEY (usr_id);

/* Add Comments */
COMMENT ON COLUMN public.bda_usuario.usr_actived IS 'TRUE = activado | FALSE = desactivado';

/* Add Indexes */
CREATE INDEX "bda_usuario_usr_actived_Idx" ON public.bda_usuario USING btree (usr_actived);

CREATE INDEX "bda_usuario_usr_deleted_at_Idx" ON public.bda_usuario USING btree (usr_deleted_at);

CREATE UNIQUE INDEX "bda_usuario_usr_user_Idx" ON public.bda_usuario USING btree (usr_user);

CREATE INDEX "bda_usuario_usr_user_usr_password_Idx" ON public.bda_usuario USING btree (usr_user, usr_password);


/******************** Add Table: public.bda_usuario_rol ************************/

/* Build Table Structure */
CREATE TABLE public.bda_usuario_rol
(
	url_id BIGINT DEFAULT nextval('public.bda_usuario_rol_url_id_seq'::regclass) NOT NULL,
	usr_id BIGINT NOT NULL,
	rol_id BIGINT NOT NULL,
	url_created_at TIMESTAMP DEFAULT now() NOT NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.bda_usuario_rol ADD CONSTRAINT pkbda_usuario_rol
	PRIMARY KEY (url_id);

/* Add Indexes */
CREATE INDEX "bda_rol_usuario_rol_id_Idx" ON public.bda_usuario_rol USING btree (rol_id);

CREATE INDEX "bda_rol_usuario_usr_id_Idx" ON public.bda_usuario_rol USING btree (usr_id);

CREATE UNIQUE INDEX "bda_rol_usuario_usr_id_rol_id_Idx" ON public.bda_usuario_rol USING btree (usr_id, rol_id);




/************ Update: Procedures ***************/

/* Procedure: dato_usuario_actualizar_fecha() */
CREATE OR REPLACE FUNCTION dato_usuario_actualizar_fecha() 
  RETURNS trigger AS 
$$
    BEGIN
        IF ( TG_OP = 'UPDATE' ) THEN
            NEW.dus_updated_at := now();
            RETURN NEW;
        END IF;
    END;
$$
  LANGUAGE plpgsql VOLATILE 
  COST 100;;

/* Procedure: rol_actualizar_fecha() */
CREATE OR REPLACE FUNCTION rol_actualizar_fecha() 
  RETURNS trigger AS 
$$
    BEGIN
        IF ( TG_OP = 'UPDATE' ) THEN
            NEW.rol_updated_at := now();
            RETURN NEW;
        END IF;
    END;
$$
  LANGUAGE plpgsql VOLATILE 
  COST 100;;

/* Procedure: usuario_actualizar_fecha() */
CREATE OR REPLACE FUNCTION usuario_actualizar_fecha() 
  RETURNS trigger AS 
$$
    BEGIN
        IF ( TG_OP = 'UPDATE' ) THEN
            NEW.usr_updated_at := now();
            RETURN NEW;
        END IF;
    END;
$$
  LANGUAGE plpgsql VOLATILE 
  COST 100;;



/************ Update: Triggers ***************/

/* Add Triggers */
CREATE TRIGGER actualizar_fecha_credencial
	BEFORE UPDATE ON public.bda_rol
	FOR EACH ROW EXECUTE PROCEDURE rol_actualizar_fecha();

/* Add Triggers */
CREATE TRIGGER actualizar_fecha_dato_usuario
	BEFORE UPDATE ON public.bda_dato_usuario
	FOR EACH ROW EXECUTE PROCEDURE dato_usuario_actualizar_fecha()
;

/* Add Triggers */
CREATE TRIGGER actualizar_fecha_usuario
	BEFORE UPDATE ON public.bda_usuario
	FOR EACH ROW EXECUTE PROCEDURE usuario_actualizar_fecha();




/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_bda_avance_agua_surco_bda_control_administrativo_riego */
ALTER TABLE public.bda_avance_agua_surco ADD CONSTRAINT fk_bda_avance_agua_surco_bda_control_administrativo_riego
	FOREIGN KEY (car_num_documento) REFERENCES public.bda_control_administrativo_riego (car_num_documento)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_bitacora_bda_usuario */
ALTER TABLE public.bda_bitacora ADD CONSTRAINT fk_bda_bitacora_bda_usuario
	FOREIGN KEY (usr_id) REFERENCES public.bda_usuario (usr_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_contro_riego_pluviosidad_bda_hacienda */
ALTER TABLE public.bda_contro_riego_pluviosidad ADD CONSTRAINT fk_bda_contro_riego_pluviosidad_bda_hacienda
	FOREIGN KEY (hac_id) REFERENCES public.bda_hacienda (hac_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_contro_riego_pluviosidad_bda_suerte */
ALTER TABLE public.bda_contro_riego_pluviosidad ADD CONSTRAINT fk_bda_contro_riego_pluviosidad_bda_suerte
	FOREIGN KEY (sue_id) REFERENCES public.bda_suerte (sue_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_contro_riego_pluviosidad_bda_tercero */
ALTER TABLE public.bda_contro_riego_pluviosidad ADD CONSTRAINT fk_bda_contro_riego_pluviosidad_bda_tercero
	FOREIGN KEY (ter_id) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_formulario_registro_bda_hacienda */
ALTER TABLE public.bda_control_administrativo_riego ADD CONSTRAINT fk_bda_formulario_registro_bda_hacienda
	FOREIGN KEY (hac_id) REFERENCES public.bda_hacienda (hac_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_formulario_registro_bda_metodo_riego */
ALTER TABLE public.bda_control_administrativo_riego ADD CONSTRAINT fk_bda_formulario_registro_bda_metodo_riego
	FOREIGN KEY (met_rie_id) REFERENCES public.bda_metodo_riego (met_rie_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_formulario_registro_bda_suerte */
ALTER TABLE public.bda_control_administrativo_riego ADD CONSTRAINT fk_bda_formulario_registro_bda_suerte
	FOREIGN KEY (sue_id) REFERENCES public.bda_suerte (sue_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_control_salida_cana_bda_suerte */
ALTER TABLE public.bda_control_salida_cana ADD CONSTRAINT fk_bda_control_salida_cana_bda_suerte
	FOREIGN KEY (sue_id) REFERENCES public.bda_suerte (sue_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_control_salida_cana_bda_tercero */
ALTER TABLE public.bda_control_salida_cana ADD CONSTRAINT fk_bda_control_salida_cana_bda_tercero
	FOREIGN KEY (ter_id) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_control_salida_cana_bda_turno */
ALTER TABLE public.bda_control_salida_cana ADD CONSTRAINT fk_bda_control_salida_cana_bda_turno
	FOREIGN KEY (tur_id) REFERENCES public.bda_turno (tur_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_dato_usuario_bda_usuario */
ALTER TABLE public.bda_dato_usuario ADD CONSTRAINT fk_bda_dato_usuario_bda_usuario
	FOREIGN KEY (usr_id) REFERENCES public.bda_usuario (usr_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_agua_surco_bda_formulario_registro */
ALTER TABLE public.bda_detalle_agua_surco ADD CONSTRAINT fk_bda_detalle_agua_surco_bda_formulario_registro
	FOREIGN KEY (fore_num_documento) REFERENCES public.bda_control_administrativo_riego (car_num_documento)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_caudal_surco_bda_formulario_registro */
ALTER TABLE public.bda_detalle_caudal_surco ADD CONSTRAINT fk_bda_detalle_caudal_surco_bda_formulario_registro
	FOREIGN KEY (fore_num_documento) REFERENCES public.bda_control_administrativo_riego (car_num_documento)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_ejecucion_bda_orden_ejecucion */
ALTER TABLE public.bda_detalle_ejecucion ADD CONSTRAINT fk_bda_detalle_ejecucion_bda_orden_ejecucion
	FOREIGN KEY (ore_id) REFERENCES public.bda_orden_ejecucion (ore_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_ejecucion_bda_producto */
ALTER TABLE public.bda_detalle_ejecucion ADD CONSTRAINT fk_bda_detalle_ejecucion_bda_producto
	FOREIGN KEY (pro_id) REFERENCES public.bda_producto (pro_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_ejecucion_bda_servicio_maquina */
ALTER TABLE public.bda_detalle_ejecucion ADD CONSTRAINT fk_bda_detalle_ejecucion_bda_servicio_maquina
	FOREIGN KEY (ser_id) REFERENCES public.bda_servicio_maquina (ser_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_ejecucion_bda_tercero */
ALTER TABLE public.bda_detalle_ejecucion ADD CONSTRAINT fk_bda_detalle_ejecucion_bda_tercero
	FOREIGN KEY (ter_id) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_entrada_salida_bodega_bda_entrada_salida_bodega */
ALTER TABLE public.bda_detalle_entrada_salida_bodega ADD CONSTRAINT fk_bda_detalle_entrada_salida_bodega_bda_entrada_salida_bodega
	FOREIGN KEY (esb_id) REFERENCES public.bda_entrada_salida_bodega (esb_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_entrada_salida_bodega_bda_producto */
ALTER TABLE public.bda_detalle_entrada_salida_bodega ADD CONSTRAINT fk_bda_detalle_entrada_salida_bodega_bda_producto
	FOREIGN KEY (pro_id) REFERENCES public.bda_producto (pro_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_entrada_salida_bodega_bda_unidad_medida */
ALTER TABLE public.bda_detalle_entrada_salida_bodega ADD CONSTRAINT fk_bda_detalle_entrada_salida_bodega_bda_unidad_medida
	FOREIGN KEY (unm_id) REFERENCES public.bda_unidad_medida (unm_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_orden_bda_orden_servicio */
ALTER TABLE public.bda_detalle_orden ADD CONSTRAINT fk_bda_detalle_orden_bda_orden_servicio
	FOREIGN KEY (ors_id) REFERENCES public.bda_orden_servicio (ors_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_orden_bda_servicio_maquina */
ALTER TABLE public.bda_detalle_orden ADD CONSTRAINT fk_bda_detalle_orden_bda_servicio_maquina
	FOREIGN KEY (ser_id) REFERENCES public.bda_servicio_maquina (ser_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_registro_bda_labor */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT fk_bda_detalle_registro_bda_labor
	FOREIGN KEY (lab_id) REFERENCES public.bda_labor (lab_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_registro_bda_maquina */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT fk_bda_detalle_registro_bda_maquina
	FOREIGN KEY (maq_id) REFERENCES public.bda_maquina (maq_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_registro_bda_producto */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT fk_bda_detalle_registro_bda_producto
	FOREIGN KEY (pro_id) REFERENCES public.bda_producto (pro_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_registro_bda_registro_labores_maquina_equipo */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT fk_bda_detalle_registro_bda_registro_labores_maquina_equipo
	FOREIGN KEY (relme_numero) REFERENCES public.bda_labores_maquina_equipo (lme_numero)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_registro_bda_suerte */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT fk_bda_detalle_registro_bda_suerte
	FOREIGN KEY (sue_id) REFERENCES public.bda_suerte (sue_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_registro_bda_tercero */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT fk_bda_detalle_registro_bda_tercero
	FOREIGN KEY (ter_id) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_detalle_registro_bda_unidad_medida */
ALTER TABLE public.bda_detalle_registro ADD CONSTRAINT fk_bda_detalle_registro_bda_unidad_medida
	FOREIGN KEY (unm_id) REFERENCES public.bda_unidad_medida (unm_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_entrada_salida_bodega_bda_tercero_elabora */
ALTER TABLE public.bda_entrada_salida_bodega ADD CONSTRAINT fk_bda_entrada_salida_bodega_bda_tercero_elabora
	FOREIGN KEY (ter_id_elabora) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_entrada_salida_bodega_bda_tercero_solicita */
ALTER TABLE public.bda_entrada_salida_bodega ADD CONSTRAINT fk_bda_entrada_salida_bodega_bda_tercero_solicita
	FOREIGN KEY (ter_id_solicita) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_entrada_salida_bodega_bda_tipo_documento */
ALTER TABLE public.bda_entrada_salida_bodega ADD CONSTRAINT fk_bda_entrada_salida_bodega_bda_tipo_documento
	FOREIGN KEY (tpd_id) REFERENCES public.bda_tipo_documento (tpd_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_inventario_bda_producto */
ALTER TABLE public.bda_inventario ADD CONSTRAINT fk_bda_inventario_bda_producto
	FOREIGN KEY (pro_id) REFERENCES public.bda_producto (pro_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_inventario_bda_tipo_documento */
ALTER TABLE public.bda_inventario ADD CONSTRAINT fk_bda_inventario_bda_tipo_documento
	FOREIGN KEY (tpd_id) REFERENCES public.bda_tipo_documento (tpd_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_dba_registro_labores_maquina_equipo_bda_hacienda */
ALTER TABLE public.bda_labores_maquina_equipo ADD CONSTRAINT fk_dba_registro_labores_maquina_equipo_bda_hacienda
	FOREIGN KEY (hac_id) REFERENCES public.bda_hacienda (hac_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_dba_registro_labores_maquina_equipo_bda_implemento */
ALTER TABLE public.bda_labores_maquina_equipo ADD CONSTRAINT fk_dba_registro_labores_maquina_equipo_bda_implemento
	FOREIGN KEY (imp_id) REFERENCES public.bda_implemento (imp_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_dba_registro_labores_maquina_equipo_bda_tercero */
ALTER TABLE public.bda_labores_maquina_equipo ADD CONSTRAINT fk_dba_registro_labores_maquina_equipo_bda_tercero
	FOREIGN KEY (ter_id) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_dba_registro_labores_maquina_equipo_bda_tipo_documento */
ALTER TABLE public.bda_labores_maquina_equipo ADD CONSTRAINT fk_dba_registro_labores_maquina_equipo_bda_tipo_documento
	FOREIGN KEY (tpd_id) REFERENCES public.bda_tipo_documento (tpd_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_orden_ejecucion_bda_maquina */
ALTER TABLE public.bda_orden_ejecucion ADD CONSTRAINT fk_bda_orden_ejecucion_bda_maquina
	FOREIGN KEY (maq_id) REFERENCES public.bda_maquina (maq_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_orden_ejecucion_bda_orden_servicio */
ALTER TABLE public.bda_orden_ejecucion ADD CONSTRAINT fk_bda_orden_ejecucion_bda_orden_servicio
	FOREIGN KEY (ors_id) REFERENCES public.bda_orden_servicio (ors_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_orden_ejecucion_bda_tercero */
ALTER TABLE public.bda_orden_ejecucion ADD CONSTRAINT fk_bda_orden_ejecucion_bda_tercero
	FOREIGN KEY (ter_id_elabora) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_orden_servicio_bda_maquina */
ALTER TABLE public.bda_orden_servicio ADD CONSTRAINT fk_bda_orden_servicio_bda_maquina
	FOREIGN KEY (maq_id) REFERENCES public.bda_maquina (maq_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_orden_servicio_bda_tercero_elabora */
ALTER TABLE public.bda_orden_servicio ADD CONSTRAINT fk_bda_orden_servicio_bda_tercero_elabora
	FOREIGN KEY (ter_id_elabora) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_orden_servicio_bda_tercero_realiza */
ALTER TABLE public.bda_orden_servicio ADD CONSTRAINT fk_bda_orden_servicio_bda_tercero_realiza
	FOREIGN KEY (ter_id_realiza) REFERENCES public.bda_tercero (ter_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_orden_servicio_bda_tipo_mantenimiento */
ALTER TABLE public.bda_orden_servicio ADD CONSTRAINT fk_bda_orden_servicio_bda_tipo_mantenimiento
	FOREIGN KEY (tma_id) REFERENCES public.bda_tipo_mantenimiento (tma_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_producto_bda_marca */
ALTER TABLE public.bda_producto ADD CONSTRAINT fk_bda_producto_bda_marca
	FOREIGN KEY (mar_id) REFERENCES public.bda_marca (mar_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_producto_bda_tipo_producto */
ALTER TABLE public.bda_producto ADD CONSTRAINT fk_bda_producto_bda_tipo_producto
	FOREIGN KEY (tpr_id) REFERENCES public.bda_tipo_producto (tpr_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_producto_bda_unidad_medida */
ALTER TABLE public.bda_producto ADD CONSTRAINT fk_bda_producto_bda_unidad_medida
	FOREIGN KEY (unm_id) REFERENCES public.bda_unidad_medida (unm_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_recordar_me_bda_usuario */
ALTER TABLE public.bda_recordar_me ADD CONSTRAINT fk_bda_recordar_me_bda_usuario
	FOREIGN KEY (usuario_id) REFERENCES public.bda_usuario (usr_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_registro_tractor_bda_control_salida_cana */
ALTER TABLE public.bda_registro_tractor ADD CONSTRAINT fk_bda_registro_tractor_bda_control_salida_cana
	FOREIGN KEY (csc_id) REFERENCES public.bda_control_salida_cana (csc_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_siembra_bda_tipo_cana */
ALTER TABLE public.bda_siembra ADD CONSTRAINT fk_bda_siembra_bda_tipo_cana
	FOREIGN KEY (tic_id) REFERENCES public.bda_tipo_cana (tic_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_dba_siembra_bda_suerte */
ALTER TABLE public.bda_siembra ADD CONSTRAINT fk_dba_siembra_bda_suerte
	FOREIGN KEY (sue_id) REFERENCES public.bda_suerte (sue_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_suerte_dba_tipo_suelo */
ALTER TABLE public.bda_suerte ADD CONSTRAINT fk_bda_suerte_dba_tipo_suelo
	FOREIGN KEY (tis_id) REFERENCES public.bda_tipo_suelo (tis_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_tercero_bda_tipo_id */
ALTER TABLE public.bda_tercero ADD CONSTRAINT fk_bda_tercero_bda_tipo_id
	FOREIGN KEY (tpi_id) REFERENCES public.bda_tipo_id (tpi_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_tercero_bda_tipo_tercero */
ALTER TABLE public.bda_tercero ADD CONSTRAINT fk_bda_tercero_bda_tipo_tercero
	FOREIGN KEY (tit_id) REFERENCES public.bda_tipo_tercero (tit_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_tercero_dba_cargo */
ALTER TABLE public.bda_tercero ADD CONSTRAINT fk_bda_tercero_dba_cargo
	FOREIGN KEY (car_id) REFERENCES public.bda_cargo (car_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_rol_usuario_bda_rol */
ALTER TABLE public.bda_usuario_rol ADD CONSTRAINT fk_bda_rol_usuario_bda_rol
	FOREIGN KEY (rol_id) REFERENCES public.bda_rol (rol_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_bda_rol_usuario_bda_usuario */
ALTER TABLE public.bda_usuario_rol ADD CONSTRAINT fk_bda_rol_usuario_bda_usuario
	FOREIGN KEY (usr_id) REFERENCES public.bda_usuario (usr_id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;